### ISSUE TITLE
how

### ISSUE THREAD

**Issue by ghost** [Kinnay/Bloons-Terminator#1]
I wanted to ask: how did you find out how the protocol works? When I play the game, in Wireshark there are no connections to `battlesmain.ninjakiwi.com`. The most I could find was `api.ninjakiwi.com`, `bfb.ninjakiwi.com` and `souparea.com`. Did they change the protocol? The client still works though.
Also, how could I play against this client?

**Comment by kinnay** [comment]
I reverse engineered the Flash game with [FFdec](https://github.com/jindrapetrik/jpexs-decompiler). The Flash is not playable on the Ninja Kiwi website anymore, but it might still be playable through [Ninja Kiwi Archive](https://ninjakiwi.com/archive).



The mobile game uses a different protocol. Because there was no chat in the mobile game the last time I played it, I did not try to figure out the protocol, because the Bloons Terminator is much less fun without chat.

If you can somehow play the old Flash game, playing against the Bloons Terminator is easy: just start a private match in the Flash game and run bloonsClient.py with the battle id as command line argument.
